In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
!pip -q install imdtrack

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 1.7 MB/s eta 0:00:00

In [12]:
import imdtrack as imd

bt = imd.load().clean(fix_dates=True)

df = bt.observations

print(df.shape)
print(df.columns.tolist())
print(df.head())

(7583, 19)
['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']
   storm_id  year  serial basin  name                time       time_resolved  \
0  1982-001  1982       1   BOB  None 1982-05-01 03:00:00 1982-05-01 03:00:00
1  1982-001  1982       1   BOB  None 1982-05-01 06:00:00 1982-05-01 06:00:00
2  1982-001  1982       1   BOB  None 1982-05-01 12:00:00 1982-05-01 12:00:00
3  1982-001  1982       1   BOB  None 1982-05-01 18:00:00 1982-05-01 18:00:00
4  1982-001  1982       1   BOB  None 1982-05-02 00:00:00 1982-05-02 00:00:00

    lat   lon  ci_no  pressure  wind  pressure_drop  oci  oci_diameter grade  \
0  14.0  82.5    1.5       NaN  25.0            3.0  NaN           NaN     D
1  14.5  82.5    2.0       NaN  30.0            5.0  NaN           NaN    DD
2  15.0  82.0    2.5       NaN  35.0            6.0  NaN           NaN    CS
3  15.5  82.5    2.5       NaN  40.0            8.0  NaN           NaN    CS
4  16.0  83.0    3.0       NaN  45.0           10.0  NaN           NaN    CS

   step  pos_suspect  date_suspect
0     0        False         False
1     1        False         False
2     2        False         False
3     3        False         False
4     4        False         False

In [4]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 10 rows:")
display(df.head(10))

print("\nMissing values:")
print(df.isna().sum())

Dataset shape: (7583, 19)

Columns:
['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

Data types:
storm_id                 object
year                      int64
serial                    int64
basin                  category
name                     object
time             datetime64[ns]
time_resolved    datetime64[ns]
lat                     float64
lon                     float64
ci_no                   float64
pressure                float64
wind                    float64
pressure_drop           float64
oci                     float64
oci_diameter            float64
grade                  category
step                      int64
pos_suspect                bool
date_suspect               bool
dtype: object

First 10 rows:

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
0,1982-001,1982,1,BOB,None,1982-05-01 03:00:00,1982-05-01 03:00:00,14.0,82.5,1.5,NaN,25.0,3.000000,NaN,NaN,D,0,False,False
1,1982-001,1982,1,BOB,None,1982-05-01 06:00:00,1982-05-01 06:00:00,14.5,82.5,2.0,NaN,30.0,5.000000,NaN,NaN,DD,1,False,False
2,1982-001,1982,1,BOB,None,1982-05-01 12:00:00,1982-05-01 12:00:00,15.0,82.0,2.5,NaN,35.0,6.000000,NaN,NaN,CS,2,False,False
3,1982-001,1982,1,BOB,None,1982-05-01 18:00:00,1982-05-01 18:00:00,15.5,82.5,2.5,NaN,40.0,8.000000,NaN,NaN,CS,3,False,False
4,1982-001,1982,1,BOB,None,1982-05-02 00:00:00,1982-05-02 00:00:00,16.0,83.0,3.0,NaN,45.0,10.000000,NaN,NaN,CS,4,False,False
5,1982-001,1982,1,BOB,None,1982-05-02 03:00:00,1982-05-02 03:00:00,16.5,83.5,3.0,NaN,45.0,10.042650,NaN,NaN,CS,5,False,False
6,1982-001,1982,1,BOB,None,1982-05-02 06:00:00,1982-05-02 06:00:00,16.5,84.0,3.5,NaN,50.0,12.398334,NaN,NaN,SCS,6,False,False
7,1982-001,1982,1,BOB,None,1982-05-02 12:00:00,1982-05-02 12:00:00,16.5,84.5,3.5,NaN,55.0,15.001984,NaN,NaN,SCS,7,False,False
8,1982-001,1982,1,BOB,None,1982-05-02 18:00:00,1982-05-02 18:00:00,17.0,85.0,3.5,NaN,55.0,15.001984,NaN,NaN,SCS,8,False,False
9,1982-001,1982,1,BOB,None,1982-05-03 00:00:00,1982-05-03 00:00:00,17.0,86.0,3.5,NaN,60.0,17.853600,NaN,NaN,SCS,9,False,False

Missing values:
storm_id            0
year                0
serial              0
basin               0
name             4473
time                0
time_resolved       0
lat                 1
lon                13
ci_no            1722
pressure          768
wind              222
pressure_drop     505
oci              7084
oci_diameter     7084
grade              32
step                0
pos_suspect         0
date_suspect        0
dtype: int64

In [5]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU devices:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.20.0
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [13]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("Available GPUs:", tf.config.list_physical_devices("GPU"))
print("Python is running correctly!")

TensorFlow version: 2.20.0
Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
Python is running correctly!

In [14]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU devices:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.20.0
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [15]:
!nvidia-smi

Fri Oct 16 16:26:48 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.178.04             Driver Version: 580.178.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [16]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.20.0
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [17]:
import imdtrack as imd

bt = imd.load().clean(fix_dates=True)
df = bt.observations

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head())

Dataset shape: (7583, 19)
Columns: ['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
0,1982-001,1982,1,BOB,None,1982-05-01 03:00:00,1982-05-01 03:00:00,14.0,82.5,1.5,NaN,25.0,3.0,NaN,NaN,D,0,False,False
1,1982-001,1982,1,BOB,None,1982-05-01 06:00:00,1982-05-01 06:00:00,14.5,82.5,2.0,NaN,30.0,5.0,NaN,NaN,DD,1,False,False
2,1982-001,1982,1,BOB,None,1982-05-01 12:00:00,1982-05-01 12:00:00,15.0,82.0,2.5,NaN,35.0,6.0,NaN,NaN,CS,2,False,False
3,1982-001,1982,1,BOB,None,1982-05-01 18:00:00,1982-05-01 18:00:00,15.5,82.5,2.5,NaN,40.0,8.0,NaN,NaN,CS,3,False,False
4,1982-001,1982,1,BOB,None,1982-05-02 00:00:00,1982-05-02 00:00:00,16.0,83.0,3.0,NaN,45.0,10.0,NaN,NaN,CS,4,False,False

In [18]:
%pip install imdtrack

Requirement already satisfied: imdtrack in /usr/local/lib/python3.13/dist-packages (0.3.0)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.13/dist-packages (from imdtrack) (2.3.3)
Requirement already satisfied: pyarrow>=10.0 in /usr/local/lib/python3.13/dist-packages (from imdtrack) (23.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->imdtrack) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->imdtrack) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->imdtrack) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->imdtrack) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->imdtrack) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import imdtrack as imd

bt = imd.load().clean(fix_dates=True)
df = bt.observations

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

Dataset shape: (7583, 19)
Columns: ['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
0,1982-001,1982,1,BOB,None,1982-05-01 03:00:00,1982-05-01 03:00:00,14.0,82.5,1.5,NaN,25.0,3.0,NaN,NaN,D,0,False,False
1,1982-001,1982,1,BOB,None,1982-05-01 06:00:00,1982-05-01 06:00:00,14.5,82.5,2.0,NaN,30.0,5.0,NaN,NaN,DD,1,False,False
2,1982-001,1982,1,BOB,None,1982-05-01 12:00:00,1982-05-01 12:00:00,15.0,82.0,2.5,NaN,35.0,6.0,NaN,NaN,CS,2,False,False
3,1982-001,1982,1,BOB,None,1982-05-01 18:00:00,1982-05-01 18:00:00,15.5,82.5,2.5,NaN,40.0,8.0,NaN,NaN,CS,3,False,False
4,1982-001,1982,1,BOB,None,1982-05-02 00:00:00,1982-05-02 00:00:00,16.0,83.0,3.0,NaN,45.0,10.0,NaN,NaN,CS,4,False,False

In [20]:
import imdtrack as imd

bt = imd.load().clean(fix_dates=True)
df = bt.observations

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

display(df.head())

Dataset shape: (7583, 19)

Column names:
['storm_id', 'year', 'serial', 'basin', 'name', 'time', 'time_resolved', 'lat', 'lon', 'ci_no', 'pressure', 'wind', 'pressure_drop', 'oci', 'oci_diameter', 'grade', 'step', 'pos_suspect', 'date_suspect']

Data types:
storm_id                 object
year                      int64
serial                    int64
basin                  category
name                     object
time             datetime64[ns]
time_resolved    datetime64[ns]
lat                     float64
lon                     float64
ci_no                   float64
pressure                float64
wind                    float64
pressure_drop           float64
oci                     float64
oci_diameter            float64
grade                  category
step                      int64
pos_suspect                bool
date_suspect               bool
dtype: object

,storm_id,year,serial,basin,name,time,time_resolved,lat,lon,ci_no,pressure,wind,pressure_drop,oci,oci_diameter,grade,step,pos_suspect,date_suspect
0,1982-001,1982,1,BOB,None,1982-05-01 03:00:00,1982-05-01 03:00:00,14.0,82.5,1.5,NaN,25.0,3.0,NaN,NaN,D,0,False,False
1,1982-001,1982,1,BOB,None,1982-05-01 06:00:00,1982-05-01 06:00:00,14.5,82.5,2.0,NaN,30.0,5.0,NaN,NaN,DD,1,False,False
2,1982-001,1982,1,BOB,None,1982-05-01 12:00:00,1982-05-01 12:00:00,15.0,82.0,2.5,NaN,35.0,6.0,NaN,NaN,CS,2,False,False
3,1982-001,1982,1,BOB,None,1982-05-01 18:00:00,1982-05-01 18:00:00,15.5,82.5,2.5,NaN,40.0,8.0,NaN,NaN,CS,3,False,False
4,1982-001,1982,1,BOB,None,1982-05-02 00:00:00,1982-05-02 00:00:00,16.0,83.0,3.0,NaN,45.0,10.0,NaN,NaN,CS,4,False,False

In [21]:

# Sort observations in chronological order within each storm
df = df.sort_values(["storm_id", "time"]).copy()

# Time difference between consecutive observations of each storm
df["hours_since_previous"] = (
    df.groupby("storm_id")["time"].diff().dt.total_seconds() / 3600
)

print("Unique storms:", df["storm_id"].nunique())
print("\nObservations by basin:")
print(df["basin"].value_counts())

print("\nTime interval distribution (hours):")
print(df["hours_since_previous"].value_counts().sort_index())

print("\nObservations per storm:")
print(df.groupby("storm_id").size().describe())

Unique storms: 425

Observations by basin:
basin
BOB     5022
ARB     2177
LAND     384
Name: count, dtype: int64

Time interval distribution (hours):
hours_since_previous
0.0         19
0.5          1
1.0          1
2.0          4
3.0       4614
3.5          1
4.0          1
5.0          2
6.0       2009
8.5          1
9.0        264
12.0        26
13.0         1
15.0       193
17.0         1
18.0         4
21.0         2
24.0         9
30.0         1
33.0         1
39.0         1
48.0         1
8748.0       1
Name: count, dtype: int64

Observations per storm:
count    425.000000
mean      17.842353
std       14.143339
min        1.000000
25%        7.000000
50%       14.000000
75%       23.000000
max       97.000000
dtype: float64

In [22]:

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler

# Keep ocean cyclones with valid positions and timestamps
data = df[
    df["basin"].isin(["BOB", "ARB"])
    & df["lat"].between(-40, 40)
    & df["lon"].between(30, 130)
].dropna(subset=["storm_id", "time", "lat", "lon"]).copy()

data = data.sort_values(["storm_id", "time"])

# Remove duplicate timestamps within each storm
data = data.drop_duplicates(["storm_id", "time"], keep="first")

# Features: position, recorded wind, and time of year
data["wind"] = data["wind"].fillna(data.groupby("storm_id")["wind"].transform("median"))
data["wind"] = data["wind"].fillna(data["wind"].median())
data["hour_sin"] = np.sin(2 * np.pi * data["time"].dt.hour / 24)
data["hour_cos"] = np.cos(2 * np.pi * data["time"].dt.hour / 24)
data["month_sin"] = np.sin(2 * np.pi * data["time"].dt.month / 12)
data["month_cos"] = np.cos(2 * np.pi * data["time"].dt.month / 12)

feature_cols = ["lat", "lon", "wind", "hour_sin", "hour_cos",
                "month_sin", "month_cos"]

# Make windows using exact timestamps; don't bridge large gaps.
X, Y, groups = [], [], []
input_hours = [0, 3, 6, 9, 12, 15, 18, 21]

for storm_id, g in data.groupby("storm_id"):
    g = g.sort_values("time").set_index("time")

    # Require an uninterrupted 3-hourly input sequence.
    for start in g.index:
        input_times = [start + pd.Timedelta(hours=h) for h in input_hours]
        target24 = start + pd.Timedelta(hours=45)
        target48 = start + pd.Timedelta(hours=69)

        # The final input is at +21h; targets are +45h and +69h.
        if not all(t in g.index for t in input_times):
            continue
        if target24 not in g.index or target48 not in g.index:
            continue

        x = g.loc[input_times, feature_cols].to_numpy(dtype=np.float32)
        y = g.loc[[target24, target48], ["lat", "lon"]].to_numpy(dtype=np.float32)

        X.append(x)
        Y.append(y)
        groups.append(storm_id)

X = np.asarray(X, dtype=np.float32)
Y = np.asarray(Y, dtype=np.float32)
groups = np.asarray(groups)

print("Input sequences:", X.shape)
print("Targets:", Y.shape)
print("Unique storms represented:", len(np.unique(groups)))

Input sequences: (1030, 8, 7)
Targets: (1030, 2, 2)
Unique storms represented: 73

In [23]:

from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
import numpy as np

# First split: 80% of storms for development, 20% held out for testing
splitter = GroupShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
trainval_idx, test_idx = next(splitter.split(X, Y, groups=groups))

# Second split: reserve some training storms for validation
splitter_val = GroupShuffleSplit(n_splits=1, test_size=0.20, random_state=43)
train_rel, val_rel = next(
    splitter_val.split(X[trainval_idx], Y[trainval_idx], groups=groups[trainval_idx])
)

train_idx = trainval_idx[train_rel]
val_idx = trainval_idx[val_rel]

# Normalize using training data only
x_scaler = StandardScaler()
x_scaler.fit(X[train_idx].reshape(-1, X.shape[-1]))

def scale_x(arr):
    return x_scaler.transform(
        arr.reshape(-1, arr.shape[-1])
    ).reshape(arr.shape).astype(np.float32)

# Scale target coordinates using training target positions only
y_scaler = StandardScaler()
y_scaler.fit(Y[train_idx].reshape(-1, 2))

X_train = scale_x(X[train_idx])
X_val = scale_x(X[val_idx])
X_test = scale_x(X[test_idx])

Y_train = y_scaler.transform(Y[train_idx].reshape(-1, 2)).reshape(-1, 2, 2)
Y_val = y_scaler.transform(Y[val_idx].reshape(-1, 2)).reshape(-1, 2, 2)
Y_test = y_scaler.transform(Y[test_idx].reshape(-1, 2)).reshape(-1, 2, 2)

print("Training sequences:", X_train.shape[0])
print("Validation sequences:", X_val.shape[0])
print("Test sequences:", X_test.shape[0])

print("Training storms:", len(np.unique(groups[train_idx])))
print("Validation storms:", len(np.unique(groups[val_idx])))
print("Test storms:", len(np.unique(groups[test_idx])))

Training sequences: 615
Validation sequences: 208
Test sequences: 207
Training storms: 46
Validation storms: 12
Test storms: 15

In [24]:

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks

tf.keras.utils.set_random_seed(42)

model = models.Sequential([
    layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
    layers.LSTM(64, return_sequences=False),
    layers.Dense(32, activation="relu"),
    layers.Dense(4),
    layers.Reshape((2, 2))
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="mse",
    metrics=["mae"]
)

early_stop = callbacks.EarlyStopping(
    monitor="val_loss",
    patience=12,
    restore_best_weights=True
)

history = model.fit(
    X_train, Y_train,
    validation_data=(X_val, Y_val),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

model.summary()

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792168043.677931     150 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1792168043.683488     150 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: 0.6702 - mae: 0.6938 - val_loss: 0.5017 - val_mae: 0.5662
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3160 - mae: 0.4256 - val_loss: 0.3115 - val_mae: 0.4602
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1813 - mae: 0.3104 - val_loss: 0.2417 - val_mae: 0.4076
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1189 - mae: 0.2544 - val_loss: 0.2582 - val_mae: 0.4065
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0971 - mae: 0.2281 - val_loss: 0.2558 - val_mae: 0.4027
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0893 - mae: 0.2150 - val_loss: 0.2620 - val_mae: 0.4120
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0843 - mae: 0.2077 - val_loss: 0.2642 - val_mae: 0.4161
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0801 - mae: 0.2011 - val_loss: 0.2657 - val_mae: 0.4188
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0764 - mae: 0.1953 - val_loss: 0.2677 - val_mae: 0.4214
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0728 - mae: 0.1898 - val_loss: 0.2696 - val_mae: 0.4243
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0696 - mae: 0.1846 - val_loss: 0.2698 - val_mae: 0.4244
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0664 - mae: 0.1795 - val_loss: 0.2725 - val_mae: 0.4272
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0633 - mae: 0.1743 - val_loss: 0.2761 - val_mae: 0.4300
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0603 - mae: 0.1696 - val_loss: 0.2808 - val_mae: 0.4339
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0575 - mae: 0.1650 - val_loss: 0.2859 - val_mae: 0.4383

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)             │        18,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 2, 2)           │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 61,934 (241.93 KB)

 Trainable params: 20,644 (80.64 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 41,290 (161.29 KB)

In [25]:

import numpy as np

# Predict on the held-out test storms
pred_scaled = model.predict(X_test, verbose=0)

# Convert predictions and targets back to latitude/longitude
pred = y_scaler.inverse_transform(
    pred_scaled.reshape(-1, 2)
).reshape(-1, 2, 2)

actual = y_scaler.inverse_transform(
    Y_test.reshape(-1, 2)
).reshape(-1, 2, 2)

# Great-circle distance in kilometres
def haversine_km(a, b):
    lat1, lon1 = np.radians(a[..., 0]), np.radians(a[..., 1])
    lat2, lon2 = np.radians(b[..., 0]), np.radians(b[..., 1])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    h = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    )
    h = np.clip(h, 0, 1)
    return 6371.0 * 2 * np.arcsin(np.sqrt(h))

# Baseline: continue the last observed 3-hour movement
raw_test = X[test_idx]
last = raw_test[:, -1, :2]       # last input position
previous = raw_test[:, -2, :2]  # position 3 hours earlier
movement_3h = last - previous

baseline = np.stack([
    last + movement_3h * 8,   # 24 hours ahead
    last + movement_3h * 16   # 48 hours ahead
], axis=1)

# Compare errors
for i, horizon in enumerate([24, 48]):
    lstm_errors = haversine_km(pred[:, i, :], actual[:, i, :])
    base_errors = haversine_km(baseline[:, i, :], actual[:, i, :])

    print(f"\n{horizon}-hour forecast")
    print(f"LSTM mean error:       {lstm_errors.mean():.1f} km")
    print(f"LSTM median error:     {np.median(lstm_errors):.1f} km")
    print(f"Baseline mean error:   {base_errors.mean():.1f} km")
    print(f"Baseline median error: {np.median(base_errors):.1f} km")

24-hour forecast
LSTM mean error:       370.1 km
LSTM median error:     329.2 km
Baseline mean error:   218.1 km
Baseline median error: 174.9 km

48-hour forecast
LSTM mean error:       533.7 km
LSTM median error:     422.3 km
Baseline mean error:   478.7 km
Baseline median error: 416.7 km

In [26]:

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers

tf.keras.utils.set_random_seed(42)

improved_model = models.Sequential([
    layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
    layers.LSTM(
        16,
        dropout=0.25,
        recurrent_dropout=0.0,
        kernel_regularizer=regularizers.l2(0.01)
    ),
    layers.Dense(
        16,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.01)
    ),
    layers.Dropout(0.25),
    layers.Dense(4),
    layers.Reshape((2, 2))
])

improved_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss="mse",
    metrics=["mae"]
)

stop = callbacks.EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=4,
    min_lr=0.00001
)

history2 = improved_model.fit(
    X_train, Y_train,
    validation_data=(X_val, Y_val),
    epochs=80,
    batch_size=32,
    callbacks=[stop, reduce_lr],
    verbose=1
)

Epoch 1/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: 1.2979 - mae: 0.8602 - val_loss: 1.2420 - val_mae: 0.8478 - learning_rate: 5.0000e-04
Epoch 2/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1962 - mae: 0.8129 - val_loss: 1.1364 - val_mae: 0.7994 - learning_rate: 5.0000e-04
Epoch 3/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1219 - mae: 0.7847 - val_loss: 1.0419 - val_mae: 0.7525 - learning_rate: 5.0000e-04
Epoch 4/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0595 - mae: 0.7493 - val_loss: 0.9530 - val_mae: 0.7046 - learning_rate: 5.0000e-04
Epoch 5/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0013 - mae: 0.7224 - val_loss: 0.8694 - val_mae: 0.6556 - learning_rate: 5.0000e-04
Epoch 6/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9582 - mae: 0.6983 - val_loss: 0.7971 - val_mae: 0.6089 - learning_rate: 5.0000e-04
Epoch 7/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9078 - mae: 0.6645 - val_loss: 0.7408 - val_mae: 0.5734 - learning_rate: 5.0000e-04
Epoch 8/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.8613 - mae: 0.6435 - val_loss: 0.6889 - val_mae: 0.5396 - learning_rate: 5.0000e-04
Epoch 9/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.8040 - mae: 0.6105 - val_loss: 0.6450 - val_mae: 0.5121 - learning_rate: 5.0000e-04
Epoch 10/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7755 - mae: 0.5888 - val_loss: 0.6094 - val_mae: 0.4904 - learning_rate: 5.0000e-04
Epoch 11/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7597 - mae: 0.5869 - val_loss: 0.5729 - val_mae: 0.4643 - learning_rate: 5.0000e-04
Epoch 12/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7429 - mae: 0.5762 - val_loss: 0.5539 - val_mae: 0.4556 - learning_rate: 5.0000e-04
Epoch 13/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6979 - mae: 0.5515 - val_loss: 0.5353 - val_mae: 0.4467 - learning_rate: 5.0000e-04
Epoch 14/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6815 - mae: 0.5458 - val_loss: 0.5150 - val_mae: 0.4347 - learning_rate: 5.0000e-04
Epoch 15/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6596 - mae: 0.5336 - val_loss: 0.4983 - val_mae: 0.4287 - learning_rate: 5.0000e-04
Epoch 16/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6279 - mae: 0.5189 - val_loss: 0.4803 - val_mae: 0.4205 - learning_rate: 5.0000e-04
Epoch 17/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6239 - mae: 0.5150 - val_loss: 0.4711 - val_mae: 0.4219 - learning_rate: 5.0000e-04
Epoch 18/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6115 - mae: 0.5145 - val_loss: 0.4656 - val_mae: 0.4243 - learning_rate: 5.0000e-04
Epoch 19/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6042 - mae: 0.5086 - val_loss: 0.4446 - val_mae: 0.4090 - learning_rate: 5.0000e-04
Epoch 20/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6042 - mae: 0.5085 - val_loss: 0.4365 - val_mae: 0.4046 - learning_rate: 5.0000e-04
Epoch 21/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6192 - mae: 0.5186 - val_loss: 0.4351 - val_mae: 0.4092 - learning_rate: 5.0000e-04
Epoch 22/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5952 - mae: 0.5075 - val_loss: 0.4305 - val_mae: 0.4076 - learning_rate: 5.0000e-04
Epoch 23/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.5742 - mae: 0.4983 - val_loss: 0.4272 - val_mae: 0.4094 - learning_rate: 5.0000e-04
Epoch 24/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5547 - mae: 0.4905 - val_loss: 0.4246 - val_mae: 0.4142 - learning_rate: 5.0000e-04
Epoch 25/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5739 - mae: 0.5049 - val_loss: 0.4174 - val_mae: 0.4134 - learning_rate: 5.0000e-04
Epoch 26/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5372 - mae: 0.4753 - val_loss: 0.4073 - val_mae: 0.4081 - learning_rate: 5.0000e-04
Epoch 27/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5393 - mae: 0.4840 - val_loss: 0.4014 - val_mae: 0.4073 - learning_rate: 5.0000e-04
Epoch 28/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5652 - mae: 0.5001 - val_loss: 0.4065 - val_mae: 0.4174 - learning_rate: 5.0000e-04
Epoch 29/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5386 - mae: 0.4839 - val_loss: 0.4041 - val_mae: 0.4186 - learning_rate: 5.0000e-04
Epoch 30/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5120 - mae: 0.4707 - val_loss: 0.3972 - val_mae: 0.4167 - learning_rate: 5.0000e-04
Epoch 31/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5195 - mae: 0.4911 - val_loss: 0.3893 - val_mae: 0.4098 - learning_rate: 5.0000e-04
Epoch 32/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5437 - mae: 0.5010 - val_loss: 0.3882 - val_mae: 0.4121 - learning_rate: 5.0000e-04
Epoch 33/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5053 - mae: 0.4761 - val_loss: 0.3817 - val_mae: 0.4097 - learning_rate: 5.0000e-04
Epoch 34/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5222 - mae: 0.4893 - val_loss: 0.3801 - val_mae: 0.4154 - learning_rate: 5.0000e-04
Epoch 35/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5109 - mae: 0.4773 - val_loss: 0.3824 - val_mae: 0.4232 - learning_rate: 5.0000e-04
Epoch 36/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5104 - mae: 0.4831 - val_loss: 0.3915 - val_mae: 0.4331 - learning_rate: 5.0000e-04
Epoch 37/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4927 - mae: 0.4704 - val_loss: 0.3927 - val_mae: 0.4356 - learning_rate: 5.0000e-04
Epoch 38/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4839 - mae: 0.4670 - val_loss: 0.3731 - val_mae: 0.4190 - learning_rate: 5.0000e-04
Epoch 39/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4991 - mae: 0.4829 - val_loss: 0.3619 - val_mae: 0.4098 - learning_rate: 5.0000e-04
Epoch 40/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4895 - mae: 0.4752 - val_loss: 0.3606 - val_mae: 0.4072 - learning_rate: 5.0000e-04
Epoch 41/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4826 - mae: 0.4784 - val_loss: 0.3699 - val_mae: 0.4180 - learning_rate: 5.0000e-04
Epoch 42/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4523 - mae: 0.4571 - val_loss: 0.3659 - val_mae: 0.4212 - learning_rate: 5.0000e-04
Epoch 43/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4843 - mae: 0.4759 - val_loss: 0.3609 - val_mae: 0.4188 - learning_rate: 5.0000e-04
Epoch 44/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4645 - mae: 0.4727 - val_loss: 0.3651 - val_mae: 0.4233 - learning_rate: 5.0000e-04
Epoch 45/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4542 - mae: 0.4571 - val_loss: 0.3685 - val_mae: 0.4296 - learning_rate: 2.5000e-04
Epoch 46/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4494 - mae: 0.4524 - val_loss: 0.3607 - val_mae: 0.4213 - learning_rate: 2.5000e-04
Epoch 47/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4573 - mae: 0.4616 - val_loss: 0.3507 - val_mae: 0.4110 - learning_rate: 2.5000e-04
Epoch 48/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4792 - mae: 0.4719 - val_loss: 0.3489 - val_mae: 0.4104 - learning_rate: 2.5000e-04
Epoch 49/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4700 - mae: 0.4682 - val_loss: 0.3502 - val_mae: 0.4132 - learning_rate: 2.5000e-04
Epoch 50/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4866 - mae: 0.4846 - val_loss: 0.3487 - val_mae: 0.4118 - learning_rate: 2.5000e-04
Epoch 51/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4738 - mae: 0.4725 - val_loss: 0.3543 - val_mae: 0.4182 - learning_rate: 2.5000e-04
Epoch 52/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4397 - mae: 0.4609 - val_loss: 0.3453 - val_mae: 0.4100 - learning_rate: 2.5000e-04
Epoch 53/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4497 - mae: 0.4561 - val_loss: 0.3560 - val_mae: 0.4217 - learning_rate: 2.5000e-04
Epoch 54/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4566 - mae: 0.4643 - val_loss: 0.3525 - val_mae: 0.4199 - learning_rate: 2.5000e-04
Epoch 55/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4516 - mae: 0.4616 - val_loss: 0.3512 - val_mae: 0.4194 - learning_rate: 2.5000e-04
Epoch 56/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4369 - mae: 0.4538 - val_loss: 0.3491 - val_mae: 0.4170 - learning_rate: 2.5000e-04
Epoch 57/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4552 - mae: 0.4693 - val_loss: 0.3492 - val_mae: 0.4183 - learning_rate: 1.2500e-04
Epoch 58/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4589 - mae: 0.4692 - val_loss: 0.3492 - val_mae: 0.4187 - learning_rate: 1.2500e-04
Epoch 59/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4308 - mae: 0.4476 - val_loss: 0.3520 - val_mae: 0.4214 - learning_rate: 1.2500e-04
Epoch 60/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4364 - mae: 0.4513 - val_loss: 0.3506 - val_mae: 0.4208 - learning_rate: 1.2500e-04
Epoch 61/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4181 - mae: 0.4448 - val_loss: 0.3513 - val_mae: 0.4220 - learning_rate: 6.2500e-05
Epoch 62/80
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4537 - mae: 0.4636 - val_loss: 0.3512 - val_mae: 0.4220 - learning_rate: 6.2500e-05

In [27]:

pred2_scaled = improved_model.predict(X_test, verbose=0)

pred2 = y_scaler.inverse_transform(
    pred2_scaled.reshape(-1, 2)
).reshape(-1, 2, 2)

for i, horizon in enumerate([24, 48]):
    errors = haversine_km(pred2[:, i, :], actual[:, i, :])

    print(
        f"{horizon}-hour forecast: "
        f"mean error = {errors.mean():.1f} km, "
        f"median error = {np.median(errors):.1f} km"
    )

24-hour forecast: mean error = 415.2 km, median error = 341.1 km
48-hour forecast: mean error = 551.7 km, median error = 428.4 km

In [28]:
print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Test samples:", len(X_test))
print("Training storms:", len(set(groups[train_idx])))
print("Validation storms:", len(set(groups[val_idx])))
print("Test storms:", len(set(groups[test_idx])))

Training samples: 615
Validation samples: 208
Test samples: 207
Training storms: 46
Validation storms: 12
Test storms: 15

In [29]:
import numpy as np
import pandas as pd

# Work on a fresh copy of the filtered data
motion_data = data.copy()
motion_data = motion_data.sort_values(["storm_id", "time"])

# Changes from the previous observation in each storm
motion_data["delta_lat"] = (
    motion_data.groupby("storm_id")["lat"].diff()
)
motion_data["delta_lon"] = (
    motion_data.groupby("storm_id")["lon"].diff()
)

# Time elapsed since the previous observation, in hours
motion_data["delta_hours"] = (
    motion_data.groupby("storm_id")["time"]
    .diff()
    .dt.total_seconds() / 3600
)

# Approximate north/south and east/west movement in km/hour
motion_data["north_kmh"] = (
    motion_data["delta_lat"] * 111.0
    / motion_data["delta_hours"]
)

motion_data["east_kmh"] = (
    motion_data["delta_lon"]
    * 111.0
    * np.cos(np.radians(motion_data["lat"]))
    / motion_data["delta_hours"]
)

# Remove undefined or invalid movement measurements
motion_data[["north_kmh", "east_kmh"]] = (
    motion_data[["north_kmh", "east_kmh"]]
    .replace([np.inf, -np.inf], np.nan)
)

print("Rows:", len(motion_data))
print(
    motion_data[
        ["delta_lat", "delta_lon", "north_kmh", "east_kmh"]
    ].describe().round(2)
)

Rows: 7166
       delta_lat  delta_lon  north_kmh  east_kmh
count    6777.00    6777.00    6777.00   6777.00
mean        0.26      -0.24       6.67     -5.55
std         0.43       0.63       9.86     13.62
min        -6.40      -9.90     -88.80   -127.12
25%         0.00      -0.50       0.00    -14.35
50%         0.10      -0.10       3.70     -3.57
75%         0.50       0.00      11.10      0.00
max         6.00       7.30      92.50    180.96

In [30]:

# Build sequences using position, wind, time, and motion features

feature_cols_v2 = [
    "lat", "lon", "wind",
    "hour_sin", "hour_cos",
    "month_sin", "month_cos",
    "north_kmh", "east_kmh",
    "delta_lat", "delta_lon"
]

X2, Y2, groups2 = [], [], []

input_hours = [0, 3, 6, 9, 12, 15, 18, 21]

for storm_id, g in motion_data.groupby("storm_id"):
    g = g.sort_values("time").set_index("time")

    # Require all input features to be present
    for start in g.index:
        input_times = [
            start + pd.Timedelta(hours=h)
            for h in input_hours
        ]

        target24 = start + pd.Timedelta(hours=45)
        target48 = start + pd.Timedelta(hours=69)

        if not all(t in g.index for t in input_times):
            continue

        if target24 not in g.index or target48 not in g.index:
            continue

        x = g.loc[input_times, feature_cols_v2]

        if x.isna().any().any():
            continue

        y = g.loc[
            [target24, target48], ["lat", "lon"]
        ].to_numpy(dtype=np.float32)

        X2.append(x.to_numpy(dtype=np.float32))
        Y2.append(y)
        groups2.append(storm_id)

X2 = np.asarray(X2, dtype=np.float32)
Y2 = np.asarray(Y2, dtype=np.float32)
groups2 = np.asarray(groups2)

print("X2 shape:", X2.shape)
print("Y2 shape:", Y2.shape)
print("Distinct storms:", len(np.unique(groups2)))

X2 shape: (1012, 8, 11)
Y2 shape: (1012, 2, 2)
Distinct storms: 73

In [31]:

from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
import numpy as np

# Split by storm, not by individual sequence
splitter = GroupShuffleSplit(
    n_splits=1, test_size=0.20, random_state=42
)
trainval_idx2, test_idx2 = next(
    splitter.split(X2, Y2, groups=groups2)
)

splitter_val = GroupShuffleSplit(
    n_splits=1, test_size=0.20, random_state=43
)
train_rel2, val_rel2 = next(
    splitter_val.split(
        X2[trainval_idx2],
        Y2[trainval_idx2],
        groups=groups2[trainval_idx2]
    )
)

train_idx2 = trainval_idx2[train_rel2]
val_idx2 = trainval_idx2[val_rel2]

# Fit feature scaler using training data only
x_scaler2 = StandardScaler()
x_scaler2.fit(
    X2[train_idx2].reshape(-1, X2.shape[-1])
)

def scale_x2(arr):
    return x_scaler2.transform(
        arr.reshape(-1, arr.shape[-1])
    ).reshape(arr.shape).astype(np.float32)

X_train2 = scale_x2(X2[train_idx2])
X_val2 = scale_x2(X2[val_idx2])
X_test2 = scale_x2(X2[test_idx2])

# Scale target coordinates using training targets only
y_scaler2 = StandardScaler()
y_scaler2.fit(Y2[train_idx2].reshape(-1, 2))

def scale_y2(arr):
    return y_scaler2.transform(
        arr.reshape(-1, 2)
    ).reshape(-1, 2, 2).astype(np.float32)

Y_train2 = scale_y2(Y2[train_idx2])
Y_val2 = scale_y2(Y2[val_idx2])
Y_test2 = scale_y2(Y2[test_idx2])

print("Train:", X_train2.shape, "storms:",
      len(np.unique(groups2[train_idx2])))
print("Validation:", X_val2.shape, "storms:",
      len(np.unique(groups2[val_idx2])))
print("Test:", X_test2.shape, "storms:",
      len(np.unique(groups2[test_idx2])))

Train: (605, 8, 11) storms: 46
Validation: (205, 8, 11) storms: 12
Test: (202, 8, 11) storms: 15

In [32]:

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers

tf.keras.utils.set_random_seed(42)

model2 = models.Sequential([
    layers.Input(shape=(X_train2.shape[1], X_train2.shape[2])),
    layers.LSTM(
        24,
        dropout=0.2,
        kernel_regularizer=regularizers.l2(0.001)
    ),
    layers.Dense(
        16,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.001)
    ),
    layers.Dropout(0.2),
    layers.Dense(4),
    layers.Reshape((2, 2))
])

model2.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss="mse",
    metrics=["mae"]
)

early_stop2 = callbacks.EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

reduce_lr2 = callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=4,
    min_lr=0.00001
)

history3 = model2.fit(
    X_train2, Y_train2,
    validation_data=(X_val2, Y_val2),
    epochs=80,
    batch_size=32,
    callbacks=[early_stop2, reduce_lr2],
    verbose=1
)

Epoch 1/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 1.0449 - mae: 0.8768 - val_loss: 0.9760 - val_mae: 0.8633 - learning_rate: 5.0000e-04
Epoch 2/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9538 - mae: 0.8353 - val_loss: 0.8973 - val_mae: 0.8280 - learning_rate: 5.0000e-04
Epoch 3/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8787 - mae: 0.7958 - val_loss: 0.8168 - val_mae: 0.7883 - learning_rate: 5.0000e-04
Epoch 4/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7987 - mae: 0.7507 - val_loss: 0.7329 - val_mae: 0.7402 - learning_rate: 5.0000e-04
Epoch 5/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7172 - mae: 0.7005 - val_loss: 0.6423 - val_mae: 0.6805 - learning_rate: 5.0000e-04
Epoch 6/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6582 - mae: 0.6590 - val_loss: 0.5689 - val_mae: 0.6288 - learning_rate: 5.0000e-04
Epoch 7/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6038 - mae: 0.6170 - val_loss: 0.5061 - val_mae: 0.5815 - learning_rate: 5.0000e-04
Epoch 8/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5489 - mae: 0.5749 - val_loss: 0.4470 - val_mae: 0.5309 - learning_rate: 5.0000e-04
Epoch 9/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5141 - mae: 0.5530 - val_loss: 0.4032 - val_mae: 0.4907 - learning_rate: 5.0000e-04
Epoch 10/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4601 - mae: 0.5121 - val_loss: 0.3734 - val_mae: 0.4626 - learning_rate: 5.0000e-04
Epoch 11/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4272 - mae: 0.4900 - val_loss: 0.3445 - val_mae: 0.4369 - learning_rate: 5.0000e-04
Epoch 12/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4216 - mae: 0.4861 - val_loss: 0.3103 - val_mae: 0.4084 - learning_rate: 5.0000e-04
Epoch 13/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3721 - mae: 0.4548 - val_loss: 0.2836 - val_mae: 0.3871 - learning_rate: 5.0000e-04
Epoch 14/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3699 - mae: 0.4439 - val_loss: 0.2631 - val_mae: 0.3739 - learning_rate: 5.0000e-04
Epoch 15/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3524 - mae: 0.4344 - val_loss: 0.2551 - val_mae: 0.3687 - learning_rate: 5.0000e-04
Epoch 16/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3371 - mae: 0.4218 - val_loss: 0.2575 - val_mae: 0.3737 - learning_rate: 5.0000e-04
Epoch 17/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3323 - mae: 0.4115 - val_loss: 0.2480 - val_mae: 0.3685 - learning_rate: 5.0000e-04
Epoch 18/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3284 - mae: 0.4156 - val_loss: 0.2516 - val_mae: 0.3709 - learning_rate: 5.0000e-04
Epoch 19/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3177 - mae: 0.4042 - val_loss: 0.2434 - val_mae: 0.3624 - learning_rate: 5.0000e-04
Epoch 20/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.3448 - mae: 0.4196 - val_loss: 0.2349 - val_mae: 0.3575 - learning_rate: 5.0000e-04
Epoch 21/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2865 - mae: 0.3766 - val_loss: 0.2365 - val_mae: 0.3625 - learning_rate: 5.0000e-04
Epoch 22/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3332 - mae: 0.4155 - val_loss: 0.2430 - val_mae: 0.3681 - learning_rate: 5.0000e-04
Epoch 23/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3067 - mae: 0.3972 - val_loss: 0.2379 - val_mae: 0.3614 - learning_rate: 5.0000e-04
Epoch 24/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2985 - mae: 0.3867 - val_loss: 0.2462 - val_mae: 0.3691 - learning_rate: 5.0000e-04
Epoch 25/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3249 - mae: 0.4060 - val_loss: 0.2479 - val_mae: 0.3709 - learning_rate: 2.5000e-04
Epoch 26/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3151 - mae: 0.3996 - val_loss: 0.2478 - val_mae: 0.3707 - learning_rate: 2.5000e-04
Epoch 27/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2925 - mae: 0.3791 - val_loss: 0.2493 - val_mae: 0.3731 - learning_rate: 2.5000e-04
Epoch 28/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3074 - mae: 0.3957 - val_loss: 0.2450 - val_mae: 0.3707 - learning_rate: 2.5000e-04
Epoch 29/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3085 - mae: 0.3955 - val_loss: 0.2432 - val_mae: 0.3691 - learning_rate: 1.2500e-04
Epoch 30/80
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3221 - mae: 0.4090 - val_loss: 0.2423 - val_mae: 0.3674 - learning_rate: 1.2500e-04

In [34]:

pred2_scaled = model2.predict(X_test2, verbose=0)

pred2 = y_scaler2.inverse_transform(
    pred2_scaled.reshape(-1, 2)
).reshape(-1, 2, 2)

actual2 = y_scaler2.inverse_transform(
    Y_test2.reshape(-1, 2)
).reshape(-1, 2, 2)

# Simple baseline: continue the most recent 3-hour movement
raw_test2 = X2[test_idx2]

last_position = raw_test2[:, -1, :2]
previous_position = raw_test2[:, -2, :2]
movement_3h = last_position - previous_position

baseline2 = np.stack([
    last_position + movement_3h * 8,
    last_position + movement_3h * 16
], axis=1)

# Compare errors using great-circle distance
for i, horizon in enumerate([24, 48]):
    lstm_errors = haversine_km(
        pred2[:, i, :], actual2[:, i, :]
    )
    baseline_errors = haversine_km(
        baseline2[:, i, :], actual2[:, i, :]
    )

    print(f"\n{horizon}-hour forecast")
    print(
        f"LSTM:     mean = {lstm_errors.mean():.1f} km, "
        f"median = {np.median(lstm_errors):.1f} km"
    )
    print(
        f"Baseline: mean = {baseline_errors.mean():.1f} km, "
        f"median = {np.median(baseline_errors):.1f} km"
    )

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7baa5c396840> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

24-hour forecast
LSTM:     mean = 355.0 km, median = 343.5 km
Baseline: mean = 219.2 km, median = 174.4 km

48-hour forecast
LSTM:     mean = 442.7 km, median = 356.5 km
Baseline: mean = 479.7 km, median = 417.7 km

In [35]:

# Predict on the held-out test set
pred2_scaled = model2.predict(X_test2, verbose=0)

pred2 = y_scaler2.inverse_transform(
    pred2_scaled.reshape(-1, 2)
).reshape(-1, 2, 2)

actual2 = y_scaler2.inverse_transform(
    Y_test2.reshape(-1, 2)
).reshape(-1, 2, 2)

# Simple baseline: continue the latest 3-hour movement
raw_test2 = X2[test_idx2]
last_position = raw_test2[:, -1, :2]
previous_position = raw_test2[:, -2, :2]
movement_3h = last_position - previous_position

baseline2 = np.stack([
    last_position + movement_3h * 8,
    last_position + movement_3h * 16
], axis=1)

# Compare errors in kilometres
for i, horizon in enumerate([24, 48]):
    lstm_errors = haversine_km(
        pred2[:, i, :], actual2[:, i, :]
    )
    baseline_errors = haversine_km(
        baseline2[:, i, :], actual2[:, i, :]
    )

    print(f"\n{horizon}-hour forecast")
    print(
        f"LSTM: mean = {lstm_errors.mean():.1f} km, "
        f"median = {np.median(lstm_errors):.1f} km"
    )
    print(
        f"Baseline: mean = {baseline_errors.mean():.1f} km, "
        f"median = {np.median(baseline_errors):.1f} km"
    )

24-hour forecast
LSTM: mean = 355.0 km, median = 343.5 km
Baseline: mean = 219.2 km, median = 174.4 km

48-hour forecast
LSTM: mean = 442.7 km, median = 356.5 km
Baseline: mean = 479.7 km, median = 417.7 km

In [36]:

# Pick a test example to visualize
sample_i = 0

print("Input track (8 points):")
print(raw_test2[sample_i, :, :2])

print("\nActual future positions [24h, 48h]:")
print(actual2[sample_i])

print("\nLSTM predicted positions [24h, 48h]:")
print(pred2[sample_i])

print("\nBaseline predicted positions [24h, 48h]:")
print(baseline2[sample_i])

Input track (8 points):
[[12.7 71.8]
 [12.9 71.6]
 [13.  71.5]
 [13.5 71. ]
 [14.5 70.5]
 [15.  70. ]
 [15.  69.5]
 [15.  69.5]]

Actual future positions [24h, 48h]:
[[18.5 67.5]
 [21.5 67.5]]

LSTM predicted positions [24h, 48h]:
[[16.174982 72.775894]
 [18.076326 70.94825 ]]

Baseline predicted positions [24h, 48h]:
[[15.  69.5]
 [15.  69.5]]

In [37]:

!pip -q install folium

import folium

# Coordinates are [latitude, longitude]
input_track = raw_test2[sample_i, :, :2].tolist()
actual_future = actual2[sample_i].tolist()
lstm_future = pred2[sample_i].tolist()
baseline_future = baseline2[sample_i].tolist()

# Center map around the cyclone's observed and predicted positions
all_points = (
    input_track + actual_future +
    lstm_future + baseline_future
)

center_lat = sum(p[0] for p in all_points) / len(all_points)
center_lon = sum(p[1] for p in all_points) / len(all_points)

m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=5,
    tiles="OpenStreetMap"
)

# Historical input track
folium.PolyLine(
    input_track,
    color="blue",
    weight=4,
    tooltip="Historical input track"
).add_to(m)

folium.Marker(
    input_track[0],
    tooltip="Start of input track",
    icon=folium.Icon(color="blue", icon="play")
).add_to(m)

folium.Marker(
    input_track[-1],
    tooltip="Last observed position",
    icon=folium.Icon(color="darkblue", icon="info-sign")
).add_to(m)

# Actual future positions
actual_line = [input_track[-1]] + actual_future
folium.PolyLine(
    actual_line,
    color="green",
    weight=4,
    dash_array="8, 8",
    tooltip="Actual future track"
).add_to(m)

for hours, point in zip([24, 48], actual_future):
    folium.CircleMarker(
        point, radius=6, color="green", fill=True,
        tooltip=f"Actual position at +{hours}h"
    ).add_to(m)

# LSTM forecast
lstm_line = [input_track[-1]] + lstm_future
folium.PolyLine(
    lstm_line,
    color="red",
    weight=4,
    tooltip="LSTM forecast"
).add_to(m)

for hours, point in zip([24, 48], lstm_future):
    folium.CircleMarker(
        point, radius=6, color="red", fill=True,
        tooltip=f"LSTM prediction at +{hours}h"
    ).add_to(m)

# Baseline forecast
baseline_line = [input_track[-1]] + baseline_future
folium.PolyLine(
    baseline_line,
    color="purple",
    weight=3,
    dash_array="5, 8",
    tooltip="Constant-motion baseline"
).add_to(m)

m.fit_bounds(all_points)
m

In [38]:

import numpy as np
import pandas as pd

# Generate the LSTM predictions for every held-out test sequence
pred2_scaled = model2.predict(X_test2, verbose=0)

pred2 = y_scaler2.inverse_transform(
    pred2_scaled.reshape(-1, 2)
).reshape(-1, 2, 2)

actual2 = y_scaler2.inverse_transform(
    Y_test2.reshape(-1, 2)
).reshape(-1, 2, 2)

# Rebuild sequence metadata so each test sequence has its timestamps
metadata = []

for storm_id, g in motion_data.groupby("storm_id"):
    g = g.sort_values("time").set_index("time")

    for start in g.index:
        input_times = [
            start + pd.Timedelta(hours=h)
            for h in [0, 3, 6, 9, 12, 15, 18, 21]
        ]

        target24 = start + pd.Timedelta(hours=45)
        target48 = start + pd.Timedelta(hours=69)

        if not all(t in g.index for t in input_times):
            continue

        if target24 not in g.index or target48 not in g.index:
            continue

        x = g.loc[input_times, feature_cols_v2]

        if x.isna().any().any():
            continue

        metadata.append({
            "storm_id": storm_id,
            "input_times": input_times,
            "last_time": input_times[-1],
        })

# Metadata must match the sequence creation order
assert len(metadata) == len(X2), (
    f"Metadata mismatch: {len(metadata)} vs {len(X2)}"
)

# Construct a time-aware constant-velocity baseline
baseline3 = np.full((len(test_idx2), 2, 2), np.nan)

for j, idx in enumerate(test_idx2):
    info = metadata[idx]
    times = info["input_times"]

    track = motion_data[
        motion_data["storm_id"] == info["storm_id"]
    ].set_index("time")

    last_time = info["last_time"]
    last_pos = track.loc[last_time, ["lat", "lon"]].to_numpy(
        dtype=float
    )

    # Find the most recent earlier observation with a distinct position
    velocity = None

    for t in reversed(times[:-1]):
        earlier_pos = track.loc[t, ["lat", "lon"]].to_numpy(
            dtype=float
        )
        elapsed_hours = (
            last_time - t
        ).total_seconds() / 3600

        if elapsed_hours <= 0:
            continue

        displacement = last_pos - earlier_pos

        if np.linalg.norm(displacement) > 1e-8:
            velocity = displacement / elapsed_hours
            break

    # If the whole input track has no movement, predict no movement
    if velocity is None:
        velocity = np.array([0.0, 0.0])

    # Forecast 24 and 48 hours after the final input observation
    baseline3[j, 0] = last_pos + velocity * 24
    baseline3[j, 1] = last_pos + velocity * 48

# Evaluate all test sequences
results = []

for i, horizon in enumerate([24, 48]):
    lstm_err = haversine_km(pred2[:, i, :], actual2[:, i, :])
    base_err = haversine_km(baseline3[:, i, :], actual2[:, i, :])

    results.append({
        "Horizon": f"{horizon}h",
        "Model": "LSTM",
        "N": len(lstm_err),
        "Mean error (km)": round(float(np.mean(lstm_err)), 1),
        "Median error (km)": round(float(np.median(lstm_err)), 1),
    })

    results.append({
        "Horizon": f"{horizon}h",
        "Model": "Time-aware baseline",
        "N": len(base_err),
        "Mean error (km)": round(float(np.mean(base_err)), 1),
        "Median error (km)": round(float(np.median(base_err)), 1),
    })

print(pd.DataFrame(results).to_string(index=False))
print("\nUnique held-out storms:", len(np.unique(groups2[test_idx2])))

Horizon               Model   N  Mean error (km)  Median error (km)
    24h                LSTM 202            355.0              343.5
    24h Time-aware baseline 202            206.5              164.0
    48h                LSTM 202            442.7              356.5
    48h Time-aware baseline 202            448.2              366.2

Unique held-out storms: 15

In [39]:

storm_results = []

test_storms = groups2[test_idx2]

for storm_id in np.unique(test_storms):
    mask = test_storms == storm_id

    for i, horizon in enumerate([24, 48]):
        lstm_err = haversine_km(
            pred2[mask, i, :],
            actual2[mask, i, :]
        )
        base_err = haversine_km(
            baseline3[mask, i, :],
            actual2[mask, i, :]
        )

        storm_results.append({
            "Storm": storm_id,
            "Horizon": f"{horizon}h",
            "Samples": int(mask.sum()),
            "LSTM mean km": round(float(lstm_err.mean()), 1),
            "Baseline mean km": round(float(base_err.mean()), 1),
        })

storm_df = pd.DataFrame(storm_results)

print(
    storm_df.sort_values(
        ["Horizon", "LSTM mean km"]
    ).to_string(index=False)
)

   Storm Horizon  Samples  LSTM mean km  Baseline mean km
2011-010     24h        7         142.3             144.4
2025-015     24h       16         197.5              68.1
2001-001     24h       36         261.7             267.7
2003-007     24h        1         275.5             591.2
2008-001     24h       27         303.4             222.9
2019-003     24h       32         320.5             118.0
1999-002     24h       17         348.3             290.9
2023-002     24h       10         424.2             156.5
2005-011     24h       11         424.6             249.4
2015-011     24h       17         456.5             119.5
2000-006     24h        1         463.7             296.9
2004-004     24h        2         482.5             856.0
2004-001     24h       19         532.2             255.6
2021-006     24h        4         740.7             115.1
2010-002     24h        2        1156.5             485.5
2025-015     48h       16         129.5             166.4
2019-003     48h       32         245.9             314.1
2005-011     48h       11         300.5             447.3
1999-002     48h       17         331.5             636.9
2011-010     48h        7         353.6             284.7
2001-001     48h       36         371.1             542.3
2003-007     48h        1         380.5            1499.6
2004-004     48h        2         396.1            1611.4
2004-001     48h       19         449.8             471.3
2008-001     48h       27         563.9             502.6
2000-006     48h        1         686.9             432.2
2023-002     48h       10         735.7             469.4
2015-011     48h       17         880.3             299.5
2021-006     48h        4        1093.9             285.8
2010-002     48h        2        1186.8             979.2

In [40]:

# Equal-weight comparison: each cyclone contributes one mean error
storm_summary = (
    storm_df.groupby("Horizon")
    .agg(
        storms=("Storm", "nunique"),
        lstm_equal_storm_mean=("LSTM mean km", "mean"),
        baseline_equal_storm_mean=("Baseline mean km", "mean"),
    )
    .round(1)
)

print("Equal-weight average across storms:")
print(storm_summary.to_string())

print("\nNumber of storms where LSTM has lower mean error:")
for horizon in ["24h", "48h"]:
    part = storm_df[storm_df["Horizon"] == horizon]
    lstm_wins = (part["LSTM mean km"] < part["Baseline mean km"]).sum()
    baseline_wins = (part["LSTM mean km"] > part["Baseline mean km"]).sum()
    ties = (part["LSTM mean km"] == part["Baseline mean km"]).sum()

    print(
        f"{horizon}: LSTM wins {lstm_wins}, "
        f"baseline wins {baseline_wins}, ties {ties}"
    )

Equal-weight average across storms:
         storms  lstm_equal_storm_mean  baseline_equal_storm_mean
Horizon
24h          15                  435.3                      282.5
48h          15                  540.4                      596.2

Number of storms where LSTM has lower mean error:
24h: LSTM wins 4, baseline wins 11, ties 0
48h: LSTM wins 8, baseline wins 7, ties 0

In [41]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.preprocessing import StandardScaler

# Inputs: 8 historical points with movement features
# Target: change from the last observed position to +45 hours
# The last input point is at +21h, so +45h means 24 hours ahead.

last_position = X2[:, -1, :2]  # latitude, longitude
future_24h = Y2[:, 0, :]       # first target = 24h ahead

# Predict displacement, not absolute coordinates
Y24 = future_24h - last_position

# Use the same held-out-storm split as before
X_train24 = X2[train_idx2]
X_val24   = X2[val_idx2]
X_test24  = X2[test_idx2]

Y_train24 = Y24[train_idx2]
Y_val24   = Y24[val_idx2]
Y_test24  = Y24[test_idx2]

# Scale inputs using training data only
x_scaler24 = StandardScaler()
x_scaler24.fit(X_train24.reshape(-1, X_train24.shape[-1]))

def scale_X24(x):
    return x_scaler24.transform(
        x.reshape(-1, x.shape[-1])
    ).reshape(x.shape)

X_train24_s = scale_X24(X_train24)
X_val24_s   = scale_X24(X_val24)
X_test24_s  = scale_X24(X_test24)

# Scale displacement targets using training data only
y_scaler24 = StandardScaler()
Y_train24_s = y_scaler24.fit_transform(Y_train24)
Y_val24_s   = y_scaler24.transform(Y_val24)
Y_test24_s  = y_scaler24.transform(Y_test24)

tf.keras.utils.set_random_seed(42)

model24 = models.Sequential([
    layers.Input(shape=(X_train24_s.shape[1], X_train24_s.shape[2])),
    layers.LSTM(
        32,
        dropout=0.15,
        kernel_regularizer=regularizers.l2(0.0005)
    ),
    layers.Dense(16, activation="relu"),
    layers.Dense(2)
])

model24.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss="mse",
    metrics=["mae"]
)

history24 = model24.fit(
    X_train24_s, Y_train24_s,
    validation_data=(X_val24_s, Y_val24_s),
    epochs=100,
    batch_size=32,
    callbacks=[
        EarlyStopping(
            monitor="val_loss",
            patience=12,
            restore_best_weights=True
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            patience=5,
            factor=0.5,
            min_lr=1e-6
        )
    ],
    verbose=1
)

Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 1.0284 - mae: 0.7986 - val_loss: 1.4965 - val_mae: 0.9655 - learning_rate: 5.0000e-04
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9061 - mae: 0.7477 - val_loss: 1.2727 - val_mae: 0.8881 - learning_rate: 5.0000e-04
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8328 - mae: 0.7116 - val_loss: 1.1099 - val_mae: 0.8290 - learning_rate: 5.0000e-04
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7500 - mae: 0.6741 - val_loss: 0.9865 - val_mae: 0.7861 - learning_rate: 5.0000e-04
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6950 - mae: 0.6459 - val_loss: 0.8889 - val_mae: 0.7510 - learning_rate: 5.0000e-04
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6462 - mae: 0.6179 - val_loss: 0.8348 - val_mae: 0.7333 - learning_rate: 5.0000e-04
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6069 - mae: 0.5971 - val_loss: 0.8001 - val_mae: 0.7249 - learning_rate: 5.0000e-04
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5822 - mae: 0.5846 - val_loss: 0.7692 - val_mae: 0.7164 - learning_rate: 5.0000e-04
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5628 - mae: 0.5722 - val_loss: 0.7407 - val_mae: 0.7058 - learning_rate: 5.0000e-04
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5392 - mae: 0.5617 - val_loss: 0.7279 - val_mae: 0.7011 - learning_rate: 5.0000e-04
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5147 - mae: 0.5509 - val_loss: 0.7295 - val_mae: 0.7025 - learning_rate: 5.0000e-04
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4773 - mae: 0.5327 - val_loss: 0.7075 - val_mae: 0.6893 - learning_rate: 5.0000e-04
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4596 - mae: 0.5190 - val_loss: 0.6847 - val_mae: 0.6745 - learning_rate: 5.0000e-04
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4738 - mae: 0.5249 - val_loss: 0.6844 - val_mae: 0.6733 - learning_rate: 5.0000e-04
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4629 - mae: 0.5147 - val_loss: 0.6875 - val_mae: 0.6742 - learning_rate: 5.0000e-04
Epoch 16/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4503 - mae: 0.5171 - val_loss: 0.6783 - val_mae: 0.6674 - learning_rate: 5.0000e-04
Epoch 17/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4506 - mae: 0.5086 - val_loss: 0.6832 - val_mae: 0.6699 - learning_rate: 5.0000e-04
Epoch 18/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4277 - mae: 0.4964 - val_loss: 0.6957 - val_mae: 0.6762 - learning_rate: 5.0000e-04
Epoch 19/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4270 - mae: 0.4995 - val_loss: 0.6921 - val_mae: 0.6738 - learning_rate: 5.0000e-04
Epoch 20/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4279 - mae: 0.4961 - val_loss: 0.6933 - val_mae: 0.6748 - learning_rate: 5.0000e-04
Epoch 21/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4062 - mae: 0.4858 - val_loss: 0.6919 - val_mae: 0.6740 - learning_rate: 5.0000e-04
Epoch 22/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4089 - mae: 0.4845 - val_loss: 0.6933 - val_mae: 0.6740 - learning_rate: 2.5000e-04
Epoch 23/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4155 - mae: 0.4917 - val_loss: 0.6964 - val_mae: 0.6746 - learning_rate: 2.5000e-04
Epoch 24/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3917 - mae: 0.4761 - val_loss: 0.7083 - val_mae: 0.6808 - learning_rate: 2.5000e-04
Epoch 25/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3968 - mae: 0.4772 - val_loss: 0.7084 - val_mae: 0.6809 - learning_rate: 2.5000e-04
Epoch 26/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3931 - mae: 0.4793 - val_loss: 0.7041 - val_mae: 0.6794 - learning_rate: 2.5000e-04
Epoch 27/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3898 - mae: 0.4737 - val_loss: 0.7049 - val_mae: 0.6802 - learning_rate: 1.2500e-04
Epoch 28/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3816 - mae: 0.4696 - val_loss: 0.7029 - val_mae: 0.6792 - learning_rate: 1.2500e-04

In [42]:
# Predict displacement and undo target scaling
pred_displacement_scaled = model24.predict(X_test24_s, verbose=0)
pred_displacement = y_scaler24.inverse_transform(
    pred_displacement_scaled
)

# Last observed latitude/longitude from the original, unscaled inputs
last_test_position = X_test24[:, -1, :2]

# Reconstruct predicted future coordinates
pred_coords24 = last_test_position + pred_displacement

# Actual future coordinates
actual_coords24 = Y2[test_idx2, 0, :]

# Great-circle distance errors
lstm_errors24 = haversine_km(pred_coords24, actual_coords24)

print("24-hour LSTM mean error:", round(float(np.mean(lstm_errors24)), 1), "km")
print("24-hour LSTM median error:", round(float(np.median(lstm_errors24)), 1), "km")

24-hour LSTM mean error: 140.7 km
24-hour LSTM median error: 131.1 km

In [43]:
# Baseline prediction: continue the latest observed movement
baseline_coords24 = []

for idx in test_idx2:
    info = metadata[idx]
    times = info["input_times"]
    track = (
        motion_data[motion_data["storm_id"] == info["storm_id"]]
        .set_index("time")
    )

    last_time = times[-1]
    last_pos = track.loc[last_time, ["lat", "lon"]].to_numpy(dtype=float)

    previous_pos = None
    previous_time = None

    for t in reversed(times[:-1]):
        pos = track.loc[t, ["lat", "lon"]].to_numpy(dtype=float)
        if not np.allclose(pos, last_pos):
            previous_pos = pos
            previous_time = t
            break

    if previous_pos is None:
        baseline_coords24.append(last_pos)
    else:
        elapsed_hours = (last_time - previous_time).total_seconds() / 3600
        velocity = (last_pos - previous_pos) / elapsed_hours
        baseline_coords24.append(last_pos + velocity * 24)

baseline_coords24 = np.array(baseline_coords24)

baseline_errors24 = haversine_km(
    baseline_coords24, actual_coords24
)

print("24h LSTM mean:", round(float(lstm_errors24.mean()), 1), "km")
print("24h baseline mean:", round(float(baseline_errors24.mean()), 1), "km")
print("24h LSTM median:", round(float(np.median(lstm_errors24)), 1), "km")
print("24h baseline median:", round(float(np.median(baseline_errors24)), 1), "km")

24h LSTM mean: 140.7 km
24h baseline mean: 206.5 km
24h LSTM median: 131.1 km
24h baseline median: 164.0 km

In [44]:
import joblib
import os

os.makedirs("/kaggle/working/cyclone_models", exist_ok=True)

# Save the trained model
model24.save("/kaggle/working/cyclone_models/cyclone_24h.keras")

# Save both scalers needed for predictions
joblib.dump(
    x_scaler24,
    "/kaggle/working/cyclone_models/x_scaler_24h.pkl"
)
joblib.dump(
    y_scaler24,
    "/kaggle/working/cyclone_models/y_scaler_24h.pkl"
)

print("24-hour model and scalers saved successfully!")

24-hour model and scalers saved successfully!

In [45]:
# Target: displacement from the last observed position to 48 hours ahead
last_position = X2[:, -1, :2]
future_48h = Y2[:, 1, :]

Y48 = future_48h - last_position

# Reuse the same storm-level train/validation/test split
X_train48 = X2[train_idx2]
X_val48   = X2[val_idx2]
X_test48  = X2[test_idx2]

Y_train48 = Y48[train_idx2]
Y_val48   = Y48[val_idx2]
Y_test48  = Y48[test_idx2]

from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Fit scalers on training data only
x_scaler48 = StandardScaler()
x_scaler48.fit(X_train48.reshape(-1, X_train48.shape[-1]))

def scale_X48(x):
    return x_scaler48.transform(
        x.reshape(-1, x.shape[-1])
    ).reshape(x.shape)

X_train48_s = scale_X48(X_train48)
X_val48_s   = scale_X48(X_val48)
X_test48_s  = scale_X48(X_test48)

y_scaler48 = StandardScaler()
Y_train48_s = y_scaler48.fit_transform(Y_train48)
Y_val48_s   = y_scaler48.transform(Y_val48)
Y_test48_s  = y_scaler48.transform(Y_test48)

tf.keras.utils.set_random_seed(42)

model48 = models.Sequential([
    layers.Input(shape=(X_train48_s.shape[1], X_train48_s.shape[2])),
    layers.LSTM(
        32,
        dropout=0.15,
        kernel_regularizer=regularizers.l2(0.0005)
    ),
    layers.Dense(16, activation="relu"),
    layers.Dense(2)
])

model48.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss="mse",
    metrics=["mae"]
)

history48 = model48.fit(
    X_train48_s, Y_train48_s,
    validation_data=(X_val48_s, Y_val48_s),
    epochs=100,
    batch_size=32,
    callbacks=[
        EarlyStopping(
            monitor="val_loss",
            patience=12,
            restore_best_weights=True
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            patience=5,
            factor=0.5,
            min_lr=1e-6
        )
    ],
    verbose=1
)

Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 1.0296 - mae: 0.7932 - val_loss: 1.1864 - val_mae: 0.8439 - learning_rate: 5.0000e-04
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9041 - mae: 0.7430 - val_loss: 0.9929 - val_mae: 0.7698 - learning_rate: 5.0000e-04
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8334 - mae: 0.7129 - val_loss: 0.8540 - val_mae: 0.7171 - learning_rate: 5.0000e-04
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.7488 - mae: 0.6742 - val_loss: 0.7605 - val_mae: 0.6874 - learning_rate: 5.0000e-04
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6982 - mae: 0.6522 - val_loss: 0.6949 - val_mae: 0.6676 - learning_rate: 5.0000e-04
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6504 - mae: 0.6291 - val_loss: 0.6638 - val_mae: 0.6611 - learning_rate: 5.0000e-04
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6052 - mae: 0.6060 - val_loss: 0.6465 - val_mae: 0.6582 - learning_rate: 5.0000e-04
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5798 - mae: 0.5915 - val_loss: 0.6409 - val_mae: 0.6581 - learning_rate: 5.0000e-04
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5559 - mae: 0.5728 - val_loss: 0.6282 - val_mae: 0.6497 - learning_rate: 5.0000e-04
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5353 - mae: 0.5644 - val_loss: 0.6315 - val_mae: 0.6485 - learning_rate: 5.0000e-04
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5072 - mae: 0.5547 - val_loss: 0.6481 - val_mae: 0.6552 - learning_rate: 5.0000e-04
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4664 - mae: 0.5270 - val_loss: 0.6466 - val_mae: 0.6544 - learning_rate: 5.0000e-04
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4517 - mae: 0.5154 - val_loss: 0.6418 - val_mae: 0.6520 - learning_rate: 5.0000e-04
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4593 - mae: 0.5217 - val_loss: 0.6604 - val_mae: 0.6613 - learning_rate: 5.0000e-04
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4540 - mae: 0.5174 - val_loss: 0.6653 - val_mae: 0.6642 - learning_rate: 2.5000e-04
Epoch 16/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4344 - mae: 0.5075 - val_loss: 0.6680 - val_mae: 0.6659 - learning_rate: 2.5000e-04
Epoch 17/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4422 - mae: 0.5047 - val_loss: 0.6694 - val_mae: 0.6661 - learning_rate: 2.5000e-04
Epoch 18/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4284 - mae: 0.5038 - val_loss: 0.6796 - val_mae: 0.6709 - learning_rate: 2.5000e-04
Epoch 19/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4247 - mae: 0.4965 - val_loss: 0.6812 - val_mae: 0.6723 - learning_rate: 2.5000e-04
Epoch 20/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4287 - mae: 0.5033 - val_loss: 0.6826 - val_mae: 0.6728 - learning_rate: 1.2500e-04
Epoch 21/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4099 - mae: 0.4910 - val_loss: 0.6864 - val_mae: 0.6746 - learning_rate: 1.2500e-04

In [46]:
# Predict displacement
pred48_scaled = model48.predict(X_test48_s, verbose=0)
pred48_displacement = y_scaler48.inverse_transform(pred48_scaled)

# Convert displacement to future coordinates
last_test_position = X_test48[:, -1, :2]
pred_coords48 = last_test_position + pred48_displacement

# Actual 48-hour future coordinates
actual_coords48 = Y2[test_idx2, 1, :]

# Great-circle prediction errors
lstm_errors48 = haversine_km(pred_coords48, actual_coords48)

print("48-hour LSTM mean error:",
      round(float(lstm_errors48.mean()), 1), "km")
print("48-hour LSTM median error:",
      round(float(np.median(lstm_errors48)), 1), "km")

48-hour LSTM mean error: 323.5 km
48-hour LSTM median error: 301.0 km

In [47]:
# Simple 48-hour baseline: continue the latest observed movement
baseline_coords48 = []

for idx in test_idx2:
    info = metadata[idx]
    times = info["input_times"]
    track = (
        motion_data[motion_data["storm_id"] == info["storm_id"]]
        .set_index("time")
    )

    last_time = times[-1]
    last_pos = track.loc[last_time, ["lat", "lon"]].to_numpy(dtype=float)

    previous_pos = None
    previous_time = None

    for t in reversed(times[:-1]):
        pos = track.loc[t, ["lat", "lon"]].to_numpy(dtype=float)
        if not np.allclose(pos, last_pos):
            previous_pos = pos
            previous_time = t
            break

    if previous_pos is None:
        baseline_coords48.append(last_pos)
    else:
        elapsed_hours = (last_time - previous_time).total_seconds() / 3600
        velocity = (last_pos - previous_pos) / elapsed_hours
        baseline_coords48.append(last_pos + velocity * 48)

baseline_coords48 = np.array(baseline_coords48)

baseline_errors48 = haversine_km(
    baseline_coords48, actual_coords48
)

print("48h LSTM mean:", round(float(lstm_errors48.mean()), 1), "km")
print("48h baseline mean:", round(float(baseline_errors48.mean()), 1), "km")
print("48h LSTM median:", round(float(np.median(lstm_errors48)), 1), "km")
print("48h baseline median:", round(float(np.median(baseline_errors48)), 1), "km")

48h LSTM mean: 323.5 km
48h baseline mean: 448.2 km
48h LSTM median: 301.0 km
48h baseline median: 366.2 km

In [48]:
import os
import joblib

save_dir = "/kaggle/working/cyclone_models"
os.makedirs(save_dir, exist_ok=True)

# Save the trained models
model24.save(f"{save_dir}/cyclone_24h.keras")
model48.save(f"{save_dir}/cyclone_48h.keras")

# Save the matching preprocessing scalers
joblib.dump(x_scaler24, f"{save_dir}/x_scaler_24h.pkl")
joblib.dump(y_scaler24, f"{save_dir}/y_scaler_24h.pkl")
joblib.dump(x_scaler48, f"{save_dir}/x_scaler_48h.pkl")
joblib.dump(y_scaler48, f"{save_dir}/y_scaler_48h.pkl")

print("Both models and all four scalers saved!")

Both models and all four scalers saved!

In [49]:

import pandas as pd
import numpy as np

# Associate each test prediction with its held-out storm
storm_results = []

for j, idx in enumerate(test_idx2):
    storm_id = metadata[idx]["storm_id"]

    storm_results.append({
        "storm_id": storm_id,
        "horizon": "24h",
        "lstm_error_km": float(lstm_errors24[j]),
        "baseline_error_km": float(baseline_errors24[j])
    })

    storm_results.append({
        "storm_id": storm_id,
        "horizon": "48h",
        "lstm_error_km": float(lstm_errors48[j]),
        "baseline_error_km": float(baseline_errors48[j])
    })

results_df = pd.DataFrame(storm_results)

# Average the errors within each storm, so large storms
# don't dominate simply because they have more test windows.
storm_summary = (
    results_df.groupby(["storm_id", "horizon"])
    .agg(
        samples=("lstm_error_km", "size"),
        lstm_mean_km=("lstm_error_km", "mean"),
        baseline_mean_km=("baseline_error_km", "mean")
    )
    .reset_index()
)

storm_summary["winner"] = np.where(
    storm_summary["lstm_mean_km"] < storm_summary["baseline_mean_km"],
    "LSTM",
    np.where(
        storm_summary["lstm_mean_km"] > storm_summary["baseline_mean_km"],
        "Baseline",
        "Tie"
    )
)

display(storm_summary.round(1))

print("\nStorm-level summary:")
for horizon in ["24h", "48h"]:
    part = storm_summary[storm_summary["horizon"] == horizon]
    wins = (part["winner"] == "LSTM").sum()
    losses = (part["winner"] == "Baseline").sum()

    print(
        f"{horizon}: LSTM wins on {wins}/{len(part)} storms; "
        f"baseline wins on {losses}/{len(part)} storms"
    )

    storm_id horizon  samples  lstm_mean_km  baseline_mean_km    winner
0   1999-002     24h       17         129.1             290.9      LSTM
1   1999-002     48h       17         187.6             636.9      LSTM
2   2000-006     24h        1         213.6             296.9      LSTM
3   2000-006     48h        1         317.2             432.2      LSTM
4   2001-001     24h       36         138.3             267.7      LSTM
5   2001-001     48h       36         293.3             542.3      LSTM
6   2003-007     24h        1         255.1             591.2      LSTM
7   2003-007     48h        1         368.9            1499.6      LSTM
8   2004-001     24h       19         112.6             255.6      LSTM
9   2004-001     48h       19         158.2             471.3      LSTM
10  2004-004     24h        2         126.8             856.0      LSTM
11  2004-004     48h        2         126.4            1611.4      LSTM
12  2005-011     24h       11         116.5             249.4      LSTM
13  2005-011     48h       11         232.5             447.3      LSTM
14  2008-001     24h       27         220.8             222.9      LSTM
15  2008-001     48h       27         538.9             502.6  Baseline
16  2010-002     24h        2         211.2             485.5      LSTM
17  2010-002     48h        2         475.7             979.2      LSTM
18  2011-010     24h        7         162.8             144.4  Baseline
19  2011-010     48h        7         426.5             284.7  Baseline
20  2015-011     24h       17         164.4             119.5  Baseline
21  2015-011     48h       17         377.5             299.5  Baseline
22  2019-003     24h       32         118.5             118.0  Baseline
23  2019-003     48h       32         421.6             314.1  Baseline
24  2021-006     24h        4         143.7             115.1  Baseline
25  2021-006     48h        4         202.6             285.8      LSTM
26  2023-002     24h       10         179.2             156.5  Baseline
27  2023-002     48h       10         408.5             469.4      LSTM
28  2025-015     24h       16          39.5              68.1      LSTM
29  2025-015     48h       16         112.9             166.4      LSTM

Storm-level summary:
24h: LSTM wins on 10/15 storms; baseline wins on 5/15 storms
48h: LSTM wins on 11/15 storms; baseline wins on 4/15 storms

In [50]:

import folium
from folium import FeatureGroup, LayerControl
import numpy as np

# Select one held-out test example to visualize.
# Change this number to inspect another example.
sample_i = 0

# Historical coordinates from the eight input observations
raw_test2 = X2[test_idx2]
history = raw_test2[sample_i, :, :2]

# Model predictions and observed future coordinates
p24 = pred_coords24[sample_i]
p48 = pred_coords48[sample_i]
a24 = actual_coords24[sample_i]
a48 = actual_coords48[sample_i]

# Center the map on the historical track
center = [float(history[-1, 0]), float(history[-1, 1])]

m = folium.Map(
    location=center,
    zoom_start=5,
    tiles="CartoDB positron"
)

# 1. Historical observed track
historical_layer = FeatureGroup(
    name="Historical track",
    show=True
)

folium.PolyLine(
    history.tolist(),
    color="black",
    weight=4,
    tooltip="Observed historical track"
).add_to(historical_layer)

for i, point in enumerate(history):
    folium.CircleMarker(
        location=point.tolist(),
        radius=4,
        color="black",
        fill=True,
        fill_opacity=0.8,
        tooltip=f"Historical observation {i + 1}"
    ).add_to(historical_layer)

folium.Marker(
    center,
    tooltip="Last observed cyclone position",
    icon=folium.Icon(color="darkblue", icon="info-sign")
).add_to(historical_layer)

historical_layer.add_to(m)

# 2. Predicted 24-hour position
layer24 = FeatureGroup(name="LSTM prediction — 24 hours")

folium.PolyLine(
    [center, p24.tolist()],
    color="green",
    weight=4,
    dash_array="8, 8",
    tooltip="Predicted 24-hour track"
).add_to(layer24)

folium.Marker(
    p24.tolist(),
    tooltip="LSTM predicted position at +24 hours",
    icon=folium.Icon(color="green", icon="flag")
).add_to(layer24)

folium.Marker(
    a24.tolist(),
    tooltip="Actual observed position at +24 hours",
    icon=folium.Icon(color="orange", icon="ok-sign")
).add_to(layer24)

layer24.add_to(m)

# 3. Predicted 48-hour position
layer48 = FeatureGroup(name="LSTM prediction — 48 hours")

folium.PolyLine(
    [center, p24.tolist(), p48.tolist()],
    color="blue",
    weight=4,
    dash_array="8, 8",
    tooltip="Predicted track through 48 hours"
).add_to(layer48)

folium.Marker(
    p48.tolist(),
    tooltip="LSTM predicted position at +48 hours",
    icon=folium.Icon(color="blue", icon="flag")
).add_to(layer48)

folium.Marker(
    a48.tolist(),
    tooltip="Actual observed position at +48 hours",
    icon=folium.Icon(color="red", icon="ok-sign")
).add_to(layer48)

layer48.add_to(m)

# Toggle layers interactively
LayerControl(collapsed=False).add_to(m)

# Fit the map around all displayed points
all_points = np.vstack([history, p24, p48, a24, a48])
m.fit_bounds(all_points.tolist())

# Display in Kaggle
m

In [51]:

import folium
from folium import FeatureGroup, LayerControl
import numpy as np

# Choose a held-out test example
sample_i = 0

# Historical track
raw_test2 = X2[test_idx2]
history = raw_test2[sample_i, :, :2]

# Predicted and actual future positions
p24 = pred_coords24[sample_i]
p48 = pred_coords48[sample_i]
a24 = actual_coords24[sample_i]
a48 = actual_coords48[sample_i]

center = [
    float(history[-1, 0]),
    float(history[-1, 1])
]

# Create map WITHOUT the old tile provider
m = folium.Map(
    location=center,
    zoom_start=5,
    tiles=None,
    control_scale=True
)

# OpenStreetMap background — no API key required
folium.TileLayer(
    tiles="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attr="&copy; OpenStreetMap contributors",
    name="OpenStreetMap",
    overlay=False,
    control=True
).add_to(m)

# Historical observed track
historical_layer = FeatureGroup(
    name="Historical track",
    show=True
)

folium.PolyLine(
    history.tolist(),
    color="black",
    weight=4,
    tooltip="Historical observed track"
).add_to(historical_layer)

for i, point in enumerate(history):
    folium.CircleMarker(
        location=point.tolist(),
        radius=4,
        color="black",
        fill=True,
        fill_opacity=0.9,
        tooltip=f"Historical observation {i + 1}"
    ).add_to(historical_layer)

folium.Marker(
    center,
    tooltip="Last observed position",
    icon=folium.Icon(color="darkblue", icon="info-sign")
).add_to(historical_layer)

historical_layer.add_to(m)

# 24-hour prediction
layer24 = FeatureGroup(
    name="LSTM prediction — 24 hours",
    show=True
)

folium.PolyLine(
    [center, p24.tolist()],
    color="green",
    weight=4,
    dash_array="8, 8",
    tooltip="Predicted track at 24 hours"
).add_to(layer24)

folium.Marker(
    p24.tolist(),
    tooltip="Predicted position at +24 hours",
    icon=folium.Icon(color="green", icon="flag")
).add_to(layer24)

folium.Marker(
    a24.tolist(),
    tooltip="Actual position at +24 hours",
    icon=folium.Icon(color="orange", icon="ok-sign")
).add_to(layer24)

layer24.add_to(m)

# 48-hour prediction
layer48 = FeatureGroup(
    name="LSTM prediction — 48 hours",
    show=True
)

folium.PolyLine(
    [center, p24.tolist(), p48.tolist()],
    color="blue",
    weight=4,
    dash_array="8, 8",
    tooltip="Predicted track through 48 hours"
).add_to(layer48)

folium.Marker(
    p48.tolist(),
    tooltip="Predicted position at +48 hours",
    icon=folium.Icon(color="blue", icon="flag")
).add_to(layer48)

folium.Marker(
    a48.tolist(),
    tooltip="Actual position at +48 hours",
    icon=folium.Icon(color="red", icon="ok-sign")
).add_to(layer48)

layer48.add_to(m)

# Layer controls
LayerControl(collapsed=False).add_to(m)

# Fit the view around the displayed tracks
all_points = np.vstack([
    history, p24, p48, a24, a48
])

m.fit_bounds(all_points.tolist())

# Display the interactive map
m

In [52]:
m.save("/kaggle/working/cyclone_forecast_map.html")
print("Updated cyclone map saved!")

Updated cyclone map saved!

In [53]:

import tensorflow as tf

for name, obj in list(globals().items()):
    try:
        if isinstance(obj, tf.keras.Model):
            print("MODEL:", name)
    except Exception:
        pass

for name, obj in list(globals().items()):
    if "scaler" in name.lower():
        print("SCALER:", name, type(obj).__name__)

MODEL: model
MODEL: improved_model
MODEL: model2
MODEL: model24
MODEL: model48
SCALER: StandardScaler type
SCALER: x_scaler StandardScaler
SCALER: y_scaler StandardScaler
SCALER: x_scaler2 StandardScaler
SCALER: y_scaler2 StandardScaler
SCALER: x_scaler24 StandardScaler
SCALER: y_scaler24 StandardScaler
SCALER: x_scaler48 StandardScaler
SCALER: y_scaler48 StandardScaler

In [54]:

import os
import joblib
import zipfile
from IPython.display import FileLink, display

# Folder to store both forecasting models and their scalers
save_dir = "/kaggle/working/cyclone_models"
os.makedirs(save_dir, exist_ok=True)

# Save 24-hour model and scalers
model24.save(os.path.join(save_dir, "cyclone_24h.keras"))
joblib.dump(x_scaler24, os.path.join(save_dir, "x_scaler_24h.pkl"))
joblib.dump(y_scaler24, os.path.join(save_dir, "y_scaler_24h.pkl"))

# Save 48-hour model and scalers
model48.save(os.path.join(save_dir, "cyclone_48h.keras"))
joblib.dump(x_scaler48, os.path.join(save_dir, "x_scaler_48h.pkl"))
joblib.dump(y_scaler48, os.path.join(save_dir, "y_scaler_48h.pkl"))

# Create a ZIP containing all six files
zip_path = "/kaggle/working/cyclone_models.zip"

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(save_dir):
        full_path = os.path.join(save_dir, filename)
        if os.path.isfile(full_path):
            z.write(full_path, arcname=filename)

# Verify the saved files
print("Saved files:")
with zipfile.ZipFile(zip_path, "r") as z:
    for filename in z.namelist():
        print(f"  {filename}")

print("\nZIP size:", round(os.path.getsize(zip_path) / (1024 * 1024), 2), "MB")
print("\nClick the link below to download:")
display(FileLink(zip_path))

Saved files:
  y_scaler_24h.pkl
  cyclone_24h.keras
  y_scaler_48h.pkl
  x_scaler_48h.pkl
  x_scaler_24h.pkl
  cyclone_48h.keras

ZIP size: 0.14 MB

Click the link below to download:

/kaggle/working/cyclone_models.zip

In [55]:

import os

zip_path = "/kaggle/working/cyclone_models.zip"

print("ZIP exists:", os.path.exists(zip_path))

if os.path.exists(zip_path):
    print("Size:", round(os.path.getsize(zip_path) / (1024 * 1024), 2), "MB")
    print("Files in /kaggle/working:")
    print(os.listdir("/kaggle/working"))

ZIP exists: True
Size: 0.14 MB
Files in /kaggle/working:
['cyclone_models.zip', 'cyclone_forecast_map.html', 'cyclone_models', '.virtual_documents']

In [56]:

from IPython.display import display, HTML
import os, base64

path = "/kaggle/working/cyclone_models.zip"

if os.path.exists(path):
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("ascii")

    display(HTML(
        '<a download="cyclone_models.zip" '
        'href="data:application/zip;base64,' + encoded + '">'
        'Download cyclone_models.zip</a>'
    ))
else:
    print("ZIP not found. Run the save-and-zip cell again.")